# Generated by Django 5.2.7 on 2025-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apichatmessage',
            name='references',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
