# Generated by Django 5.2.6 on 2025-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_customuser_is_main_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
