# Generated by Django 5.2.7 on 2025-11-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
