# Generated by Django 5.2.7 on 2025-12-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('index_path', models.CharField(max_length=500)),
                ('total_chunks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='members.uploadedfile')),
            ],
        ),
    ]
