# Generated by Django 5.2.7 on 2025-12-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_interviewquestion_interviewresponse_interviewsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='cv_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
