# Generated by Django 5.2.7 on 2025-10-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotqa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
