# Generated by Django 5.2.7 on 2025-10-24 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_chatbotqa_uploaded_file_alter_uploadedfile_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotqa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chatbot QA', 'verbose_name_plural': 'Chatbot QAs'},
        ),
        migrations.AlterField(
            model_name='chatbotqa',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_from_file', to='members.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='chatbotqa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_qas', to=settings.AUTH_USER_MODEL),
        ),
    ]
