# Generated by Django 5.2.7 on 2025-10-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_chatbotqa_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotqa',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_from_file', to='members.uploadedfile'),
        ),
    ]
